version: '3'
      
services: 
  vpn:
    image: dperson/openvpn-client:latest
    container_name: vpn
    restart: unless-stopped
    cap_add:
     - NET_ADMIN
    sysctls:
     - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
     - label:disable
    environment:
     - PUID=1001
     - PGID=1003
     - TZ=Europe/Paris
    networks:
     - vpn-network
    dns:
     - 1.1.1.1
     - 1.0.0.1
    ports:
      - 8080:8080
    devices:
     - /dev/net/tun:/dev/net/tun
    expose:
     - "45000"
    volumes:
     - /home/docker-compose/vpn/config:/vpn
    command: '-f "" -r 192.168.0.0/24'
    healthcheck:
      test: ["CMD", "curl", "-Ss", "ifconfig.co"]
      interval: 60s
      timeout: 15s
      
networks:
  vpn-network:
    external:
      name: vpn-network
